In [1]:
import numpy as np

In [2]:
import pandas as pd
dataset=pd.read_csv("C:\\Users\\sharv\\ANN\\Churn.csv")

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X=dataset.iloc[:, 3:13].values
X.shape

(10000, 10)

In [5]:
y=dataset.iloc[:,13].values
y.shape

(10000,)

In [6]:
X[1:10]

array([[608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
le_x_1=LabelEncoder()
X[:,1]=le_x_1.fit_transform(X[:,1])
le_x_2=LabelEncoder()
X[:,2]=le_x_2.fit_transform(X[:,2])
X[1:10]

array([[608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 2, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 0, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 1, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 0, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 0, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]], dtype=object)

In [9]:
ohc=ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X=ohc.fit_transform(X)
X[1:10]

array([[0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [0.0, 1.0, 0.0, 376, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [1.0, 0.0, 0.0, 501, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [1.0, 0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [10]:
X=X[:,1:]

In [11]:
X[1:10]

array([[0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [1.0, 0.0, 376, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [0.0, 0.0, 501, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [12]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=0)
print(X_train.shape,X_train.shape)
X_train.shape,X_test

(8000, 11) (8000, 11)


((8000, 11),
 array([[1.0, 0.0, 597, ..., 1, 1, 192852.67],
        [0.0, 0.0, 523, ..., 1, 0, 128702.1],
        [0.0, 1.0, 706, ..., 1, 1, 75732.25],
        ...,
        [0.0, 1.0, 578, ..., 1, 0, 141533.19],
        [1.0, 0.0, 650, ..., 1, 1, 11276.48],
        [1.0, 0.0, 573, ..., 1, 0, 192950.6]], dtype=object))

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train.shape,X_test

((8000, 11),
 array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
          0.9687384 ,  1.61085707],
        [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
         -1.03227043,  0.49587037],
        [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
          0.9687384 , -0.42478674],
        ...,
        [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
         -1.03227043,  0.71888467],
        [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
          0.9687384 , -1.54507805],
        [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
         -1.03227043,  1.61255917]]))

In [14]:
import tensorflow.keras
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [15]:
classifier = Sequential()

In [16]:
classifier.add(Dense(6,input_dim=11,kernel_initializer='uniform',activation='relu'))

In [17]:
classifier.add(Dense(6,kernel_initializer='uniform',activation='relu'))

In [18]:
classifier.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))

In [19]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Train on 8000 samples
Epoch 1/100
  10/8000 [..............................] - ETA: 5:16:40

InternalError:  Blas GEMM launch failed : a.shape=(10, 11), b.shape=(11, 6), m=10, n=6, k=11
	 [[node sequential/dense/MatMul (defined at <ipython-input-20-4d84385f8ad1>:1) ]] [Op:__inference_distributed_function_741]

Function call stack:
distributed_function


In [37]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [38]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1529,   66],
       [ 251,  154]], dtype=int64)

In [39]:
###Epoch 100/100 : 800/800 [==============================] - 1s 2ms/step - loss: 0.4000 - accuracy: 0.8341
#array([[1542,   53],
#       [ 259,  146]], dtype=int64)

In [40]:
(cm[0,0]+cm[1,1])/2000

0.8415